export const SIGN_IN_USER="api/employee/signIn"
export const GET_FORMATED_ATTENDANCE_BY_ID="api/attendance/process"


const  CATEGORY_LEVELS = [
    {
      id: 1,
      label: 'Technical',
    },
    {
      id: 2,
      label: 'Business',
    },
  
];

const COUNTRY_DETAILS = [
  {
    code: 'AF',
    dial_code: '+93',
    emoji: '🇦🇫',
    name: 'Afghanistan',
    nameEmoji: '🇦🇫 Afghanistan',
  },
  {
    code: 'AX',
    dial_code: '+358',
    emoji: '🇦🇽',
    name: 'Aland Islands',
    nameEmoji: '🇦🇽 Aland Islands',
  },
  {
    code: 'AL',
    dial_code: '+355',
    emoji: '🇦🇱',
    name: 'Albania',
    nameEmoji: '🇦🇱 Albania',
  },
  {
    code: 'DZ',
    dial_code: '+213',
    emoji: '🇩🇿',
    name: 'Algeria',
    nameEmoji: '🇩🇿 Algeria',
  },
  {
    code: 'AS',
    dial_code: '+1684',
    emoji: '🇦🇸',
    name: 'AmericanSamoa',
    nameEmoji: '🇦🇸 AmericanSamoa',
  },
  {
    code: 'AD',
    dial_code: '+376',
    emoji: '🇦🇩',
    name: 'Andorra',
    nameEmoji: '🇦🇩 Andorra',
  },
  {
    code: 'AO',
    dial_code: '+244',
    emoji: '🇦🇴',
    name: 'Angola',
    nameEmoji: '🇦🇴 Angola',
  },
  {
    code: 'AI',
    dial_code: '+1264',
    emoji: '🇦🇮',
    name: 'Anguilla',
    nameEmoji: '🇦🇮 Anguilla',
  },
  {
    code: 'AQ',
    dial_code: '+672',
    emoji: '🇦🇶',
    name: 'Antarctica',
    nameEmoji: '🇦🇶 Antarctica',
  },
  {
    code: 'AG',
    dial_code: '+1268',
    emoji: '🇦🇬',
    name: 'Antigua and Barbuda',
    nameEmoji: '🇦🇬 Antigua and Barbuda',
  },
  {
    code: 'AR',
    dial_code: '+54',
    emoji: '🇦🇷',
    name: 'Argentina',
    nameEmoji: '🇦🇷 Argentina',
  },
  {
    code: 'AM',
    dial_code: '+374',
    emoji: '🇦🇲',
    name: 'Armenia',
    nameEmoji: '🇦🇲 Armenia',
  },
  {
    code: 'AW',
    dial_code: '+297',
    emoji: '🇦🇼',
    name: 'Aruba',
    nameEmoji: '🇦🇼 Aruba',
  },
  {
    code: 'AU',
    dial_code: '+61',
    emoji: '🇦🇺',
    name: 'Australia',
    nameEmoji: '🇦🇺 Australia',
  },
  {
    code: 'AT',
    dial_code: '+43',
    emoji: '🇦🇹',
    name: 'Austria',
    nameEmoji: '🇦🇹 Austria',
  },
  {
    code: 'AZ',
    dial_code: '+994',
    emoji: '🇦🇿',
    name: 'Azerbaijan',
    nameEmoji: '🇦🇿 Azerbaijan',
  },
  {
    code: 'BS',
    dial_code: '+1242',
    emoji: '🇧🇸',
    name: 'Bahamas',
    nameEmoji: '🇧🇸 Bahamas',
  },
  {
    code: 'BH',
    dial_code: '+973',
    emoji: '🇧🇭',
    name: 'Bahrain',
    nameEmoji: '🇧🇭 Bahrain',
  },
  {
    code: 'BD',
    dial_code: '+880',
    emoji: '🇧🇩',
    name: 'Bangladesh',
    nameEmoji: '🇧🇩 Bangladesh',
  },
  {
    code: 'BB',
    dial_code: '+1246',
    emoji: '🇧🇧',
    name: 'Barbados',
    nameEmoji: '🇧🇧 Barbados',
  },
  {
    code: 'BY',
    dial_code: '+375',
    emoji: '🇧🇾',
    name: 'Belarus',
    nameEmoji: '🇧🇾 Belarus',
  },
  {
    code: 'BE',
    dial_code: '+32',
    emoji: '🇧🇪',
    name: 'Belgium',
    nameEmoji: '🇧🇪 Belgium',
  },
  {
    code: 'BZ',
    dial_code: '+501',
    emoji: '🇧🇿',
    name: 'Belize',
    nameEmoji: '🇧🇿 Belize',
  },
  {
    code: 'BJ',
    dial_code: '+229',
    emoji: '🇧🇯',
    name: 'Benin',
    nameEmoji: '🇧🇯 Benin',
  },
  {
    code: 'BM',
    dial_code: '+1441',
    emoji: '🇧🇲',
    name: 'Bermuda',
    nameEmoji: '🇧🇲 Bermuda',
  },
  {
    code: 'BT',
    dial_code: '+975',
    emoji: '🇧🇹',
    name: 'Bhutan',
    nameEmoji: '🇧🇹 Bhutan',
  },
  {
    code: 'BO',
    dial_code: '+591',
    emoji: '🇧🇴',
    name: 'Bolivia, Plurinational State of',
    nameEmoji: '🇧🇴 Bolivia, Plurinational State of',
  },
  {
    code: 'BA',
    dial_code: '+387',
    emoji: '🇧🇦',
    name: 'Bosnia and Herzegovina',
    nameEmoji: '🇧🇦 Bosnia and Herzegovina',
  },
  {
    code: 'BW',
    dial_code: '+267',
    emoji: '🇧🇼',
    name: 'Botswana',
    nameEmoji: '🇧🇼 Botswana',
  },
  {
    code: 'BR',
    dial_code: '+55',
    emoji: '🇧🇷',
    name: 'Brazil',
    nameEmoji: '🇧🇷 Brazil',
  },
  {
    code: 'IO',
    dial_code: '+246',
    emoji: '🇮🇴',
    name: 'British Indian Ocean Territory',
    nameEmoji: '🇮🇴 British Indian Ocean Territory',
  },
  {
    code: 'BN',
    dial_code: '+673',
    emoji: '🇧🇳',
    name: 'Brunei Darussalam',
    nameEmoji: '🇧🇳 Brunei Darussalam',
  },
  {
    code: 'BG',
    dial_code: '+359',
    emoji: '🇧🇬',
    name: 'Bulgaria',
    nameEmoji: '🇧🇬 Bulgaria',
  },
  {
    code: 'BF',
    dial_code: '+226',
    emoji: '🇧🇫',
    name: 'Burkina Faso',
    nameEmoji: '🇧🇫 Burkina Faso',
  },
  {
    code: 'BI',
    dial_code: '+257',
    emoji: '🇧🇮',
    name: 'Burundi',
    nameEmoji: '🇧🇮 Burundi',
  },
  {
    code: 'KH',
    dial_code: '+855',
    emoji: '🇰🇭',
    name: 'Cambodia',
    nameEmoji: '🇰🇭 Cambodia',
  },
  {
    code: 'CM',
    dial_code: '+237',
    emoji: '🇨🇲',
    name: 'Cameroon',
    nameEmoji: '🇨🇲 Cameroon',
  },
  {
    code: 'CA',
    dial_code: '+1',
    emoji: '🇨🇦',
    name: 'Canada',
    nameEmoji: '🇨🇦 Canada',
  },
  {
    code: 'CV',
    dial_code: '+238',
    emoji: '🇨🇻',
    name: 'Cape Verde',
    nameEmoji: '🇨🇻 Cape Verde',
  },
  {
    code: 'KY',
    dial_code: '+345',
    emoji: '🇰🇾',
    name: 'Cayman Islands',
    nameEmoji: '🇰🇾 Cayman Islands',
  },
  {
    code: 'CF',
    dial_code: '+236',
    emoji: '🇨🇫',
    name: 'Central African Republic',
    nameEmoji: '🇨🇫 Central African Republic',
  },
  {
    code: 'TD',
    dial_code: '+235',
    emoji: '🇹🇩',
    name: 'Chad',
    nameEmoji: '🇹🇩 Chad',
  },
  {
    code: 'CL',
    dial_code: '+56',
    emoji: '🇨🇱',
    name: 'Chile',
    nameEmoji: '🇨🇱 Chile',
  },
  {
    code: 'CN',
    dial_code: '+86',
    emoji: '🇨🇳',
    name: 'China',
    nameEmoji: '🇨🇳 China',
  },
  {
    code: 'CX',
    dial_code: '+61',
    emoji: '🇨🇽',
    name: 'Christmas Island',
    nameEmoji: '🇨🇽 Christmas Island',
  },
  {
    code: 'CC',
    dial_code: '+61',
    emoji: '🇨🇨',
    name: 'Cocos (Keeling) Islands',
    nameEmoji: '🇨🇨 Cocos (Keeling) Islands',
  },
  {
    code: 'CO',
    dial_code: '+57',
    emoji: '🇨🇴',
    name: 'Colombia',
    nameEmoji: '🇨🇴 Colombia',
  },
  {
    code: 'KM',
    dial_code: '+269',
    emoji: '🇰🇲',
    name: 'Comoros',
    nameEmoji: '🇰🇲 Comoros',
  },
  {
    code: 'CG',
    dial_code: '+242',
    emoji: '🇨🇬',
    name: 'Congo',
    nameEmoji: '🇨🇬 Congo',
  },
  {
    code: 'CD',
    dial_code: '+243',
    emoji: '🇨🇩',
    name: 'Congo, The Democratic Republic of the Congo',
    nameEmoji: '🇨🇩 Congo, The Democratic Republic of the Congo',
  },
  {
    code: 'CK',
    dial_code: '+682',
    emoji: '🇨🇰',
    name: 'Cook Islands',
    nameEmoji: '🇨🇰 Cook Islands',
  },
  {
    code: 'CR',
    dial_code: '+506',
    emoji: '🇨🇷',
    name: 'Costa Rica',
    nameEmoji: '🇨🇷 Costa Rica',
  },
  {
    code: 'CI',
    dial_code: '+225',
    emoji: '🇨🇮',
    name: "Cote d'Ivoire",
    nameEmoji: "🇨🇮 Cote d'Ivoire",
  },
  {
    code: 'HR',
    dial_code: '+385',
    emoji: '🇭🇷',
    name: 'Croatia',
    nameEmoji: '🇭🇷 Croatia',
  },
  {
    code: 'CU',
    dial_code: '+53',
    emoji: '🇨🇺',
    name: 'Cuba',
    nameEmoji: '🇨🇺 Cuba',
  },
  {
    code: 'CY',
    dial_code: '+357',
    emoji: '🇨🇾',
    name: 'Cyprus',
    nameEmoji: '🇨🇾 Cyprus',
  },
  {
    code: 'CZ',
    dial_code: '+420',
    emoji: '🇨🇿',
    name: 'Czech Republic',
    nameEmoji: '🇨🇿 Czech Republic',
  },
  {
    code: 'DK',
    dial_code: '+45',
    emoji: '🇩🇰',
    name: 'Denmark',
    nameEmoji: '🇩🇰 Denmark',
  },
  {
    code: 'DJ',
    dial_code: '+253',
    emoji: '🇩🇯',
    name: 'Djibouti',
    nameEmoji: '🇩🇯 Djibouti',
  },
  {
    code: 'DM',
    dial_code: '+1767',
    emoji: '🇩🇲',
    name: 'Dominica',
    nameEmoji: '🇩🇲 Dominica',
  },
  {
    code: 'DO',
    dial_code: '+1849',
    emoji: '🇩🇴',
    name: 'Dominican Republic',
    nameEmoji: '🇩🇴 Dominican Republic',
  },
  {
    code: 'EC',
    dial_code: '+593',
    emoji: '🇪🇨',
    name: 'Ecuador',
    nameEmoji: '🇪🇨 Ecuador',
  },
  {
    code: 'EG',
    dial_code: '+20',
    emoji: '🇪🇬',
    name: 'Egypt',
    nameEmoji: '🇪🇬 Egypt',
  },
  {
    code: 'SV',
    dial_code: '+503',
    emoji: '🇸🇻',
    name: 'El Salvador',
    nameEmoji: '🇸🇻 El Salvador',
  },
  {
    code: 'GQ',
    dial_code: '+240',
    emoji: '🇬🇶',
    name: 'Equatorial Guinea',
    nameEmoji: '🇬🇶 Equatorial Guinea',
  },
  {
    code: 'ER',
    dial_code: '+291',
    emoji: '🇪🇷',
    name: 'Eritrea',
    nameEmoji: '🇪🇷 Eritrea',
  },
  {
    code: 'EE',
    dial_code: '+372',
    emoji: '🇪🇪',
    name: 'Estonia',
    nameEmoji: '🇪🇪 Estonia',
  },
  {
    code: 'ET',
    dial_code: '+251',
    emoji: '🇪🇹',
    name: 'Ethiopia',
    nameEmoji: '🇪🇹 Ethiopia',
  },
  {
    code: 'FK',
    dial_code: '+500',
    emoji: '🇫🇰',
    name: 'Falkland Islands (Malvinas)',
    nameEmoji: '🇫🇰 Falkland Islands (Malvinas)',
  },
  {
    code: 'FO',
    dial_code: '+298',
    emoji: '🇫🇴',
    name: 'Faroe Islands',
    nameEmoji: '🇫🇴 Faroe Islands',
  },
  {
    code: 'FJ',
    dial_code: '+679',
    emoji: '🇫🇯',
    name: 'Fiji',
    nameEmoji: '🇫🇯 Fiji',
  },
  {
    code: 'FI',
    dial_code: '+358',
    emoji: '🇫🇮',
    name: 'Finland',
    nameEmoji: '🇫🇮 Finland',
  },
  {
    code: 'FR',
    dial_code: '+33',
    emoji: '🇫🇷',
    name: 'France',
    nameEmoji: '🇫🇷 France',
  },
  {
    code: 'GF',
    dial_code: '+594',
    emoji: '🇬🇫',
    name: 'French Guiana',
    nameEmoji: '🇬🇫 French Guiana',
  },
  {
    code: 'PF',
    dial_code: '+689',
    emoji: '🇵🇫',
    name: 'French Polynesia',
    nameEmoji: '🇵🇫 French Polynesia',
  },
  {
    code: 'GA',
    dial_code: '+241',
    emoji: '🇬🇦',
    name: 'Gabon',
    nameEmoji: '🇬🇦 Gabon',
  },
  {
    code: 'GM',
    dial_code: '+220',
    emoji: '🇬🇲',
    name: 'Gambia',
    nameEmoji: '🇬🇲 Gambia',
  },
  {
    code: 'GE',
    dial_code: '+995',
    emoji: '🇬🇪',
    name: 'Georgia',
    nameEmoji: '🇬🇪 Georgia',
  },
  {
    code: 'DE',
    dial_code: '+49',
    emoji: '🇩🇪',
    name: 'Germany',
    nameEmoji: '🇩🇪 Germany',
  },
  {
    code: 'GH',
    dial_code: '+233',
    emoji: '🇬🇭',
    name: 'Ghana',
    nameEmoji: '🇬🇭 Ghana',
  },
  {
    code: 'GI',
    dial_code: '+350',
    emoji: '🇬🇮',
    name: 'Gibraltar',
    nameEmoji: '🇬🇮 Gibraltar',
  },
  {
    code: 'GR',
    dial_code: '+30',
    emoji: '🇬🇷',
    name: 'Greece',
    nameEmoji: '🇬🇷 Greece',
  },
  {
    code: 'GL',
    dial_code: '+299',
    emoji: '🇬🇱',
    name: 'Greenland',
    nameEmoji: '🇬🇱 Greenland',
  },
  {
    code: 'GD',
    dial_code: '+1473',
    emoji: '🇬🇩',
    name: 'Grenada',
    nameEmoji: '🇬🇩 Grenada',
  },
  {
    code: 'GP',
    dial_code: '+590',
    emoji: '🇬🇵',
    name: 'Guadeloupe',
    nameEmoji: '🇬🇵 Guadeloupe',
  },
  {
    code: 'GU',
    dial_code: '+1671',
    emoji: '🇬🇺',
    name: 'Guam',
    nameEmoji: '🇬🇺 Guam',
  },
  {
    code: 'GT',
    dial_code: '+502',
    emoji: '🇬🇹',
    name: 'Guatemala',
    nameEmoji: '🇬🇹 Guatemala',
  },
  {
    code: 'GG',
    dial_code: '+44',
    emoji: '🇬🇬',
    name: 'Guernsey',
    nameEmoji: '🇬🇬 Guernsey',
  },
  {
    code: 'GN',
    dial_code: '+224',
    emoji: '🇬🇳',
    name: 'Guinea',
    nameEmoji: '🇬🇳 Guinea',
  },
  {
    code: 'GW',
    dial_code: '+245',
    emoji: '🇬🇼',
    name: 'Guinea-Bissau',
    nameEmoji: '🇬🇼 Guinea-Bissau',
  },
  {
    code: 'GY',
    dial_code: '+595',
    emoji: '🇬🇾',
    name: 'Guyana',
    nameEmoji: '🇬🇾 Guyana',
  },
  {
    code: 'HT',
    dial_code: '+509',
    emoji: '🇭🇹',
    name: 'Haiti',
    nameEmoji: '🇭🇹 Haiti',
  },
  {
    code: 'VA',
    dial_code: '+379',
    emoji: '🇻🇦',
    name: 'Holy See (Vatican City State)',
    nameEmoji: '🇻🇦 Holy See (Vatican City State)',
  },
  {
    code: 'HN',
    dial_code: '+504',
    emoji: '🇭🇳',
    name: 'Honduras',
    nameEmoji: '🇭🇳 Honduras',
  },
  {
    code: 'HK',
    dial_code: '+852',
    emoji: '🇭🇰',
    name: 'Hong Kong',
    nameEmoji: '🇭🇰 Hong Kong',
  },
  {
    code: 'HU',
    dial_code: '+36',
    emoji: '🇭🇺',
    name: 'Hungary',
    nameEmoji: '🇭🇺 Hungary',
  },
  {
    code: 'IS',
    dial_code: '+354',
    emoji: '🇮🇸',
    name: 'Iceland',
    nameEmoji: '🇮🇸 Iceland',
  },
  {
    code: 'IN',
    dial_code: '+91',
    emoji: '🇮🇳',
    name: 'India',
    nameEmoji: '🇮🇳 India',
  },
  {
    code: 'ID',
    dial_code: '+62',
    emoji: '🇮🇩',
    name: 'Indonesia',
    nameEmoji: '🇮🇩 Indonesia',
  },
  {
    code: 'IR',
    dial_code: '+98',
    emoji: '🇮🇷',
    name: 'Iran, Islamic Republic of Persian Gulf',
    nameEmoji: '🇮🇷 Iran, Islamic Republic of Persian Gulf',
  },
  {
    code: 'IQ',
    dial_code: '+964',
    emoji: '🇮🇷',
    name: 'Iraq',
    nameEmoji: '🇮🇷 Iraq',
  },
  {
    code: 'IE',
    dial_code: '+353',
    emoji: '🇮🇪',
    name: 'Ireland',
    nameEmoji: '🇮🇪 Ireland',
  },
  {
    code: 'IM',
    dial_code: '+44',
    emoji: '🇮🇲',
    name: 'Isle of Man',
    nameEmoji: '🇮🇲 Isle of Man',
  },
  {
    code: 'IL',
    dial_code: '+972',
    emoji: '🇮🇱',
    name: 'Israel',
    nameEmoji: '🇮🇱 Israel',
  },
  {
    code: 'IT',
    dial_code: '+39',
    emoji: '🇮🇹',
    name: 'Italy',
    nameEmoji: '🇮🇹 Italy',
  },
  {
    code: 'JM',
    dial_code: '+1876',
    emoji: '🇯🇲',
    name: 'Jamaica',
    nameEmoji: '🇯🇲 Jamaica',
  },
  {
    code: 'JP',
    dial_code: '+81',
    emoji: '🇯🇵',
    name: 'Japan',
    nameEmoji: '🇯🇵 Japan',
  },
  {
    code: 'JE',
    dial_code: '+44',
    emoji: '🇯🇪',
    name: 'Jersey',
    nameEmoji: '🇯🇪 Jersey',
  },
  {
    code: 'JO',
    dial_code: '+962',
    emoji: '🇯🇴',
    name: 'Jordan',
    nameEmoji: '🇯🇴 Jordan',
  },
  {
    code: 'KZ',
    dial_code: '+77',
    emoji: '🇰🇿',
    name: 'Kazakhstan',
    nameEmoji: '🇰🇿 Kazakhstan',
  },
  {
    code: 'KE',
    dial_code: '+254',
    emoji: '🇰🇪',
    name: 'Kenya',
    nameEmoji: '🇰🇪 Kenya',
  },
  {
    code: 'KI',
    dial_code: '+686',
    emoji: '🇰🇮',
    name: 'Kiribati',
    nameEmoji: '🇰🇮 Kiribati',
  },
  {
    code: 'KP',
    dial_code: '+850',
    emoji: '🇰🇵',
    name: "Korea, Democratic People's Republic of Korea",
    nameEmoji: "🇰🇵 Korea, Democratic People's Republic of Korea",
  },
  {
    code: 'KR',
    dial_code: '+82',
    emoji: '🇰🇷',
    name: 'Korea, Republic of South Korea',
    nameEmoji: '🇰🇷 Korea, Republic of South Korea',
  },
  {
    code: 'KW',
    dial_code: '+965',
    emoji: '🇰🇼',
    name: 'Kuwait',
    nameEmoji: '🇰🇼 Kuwait',
  },
  {
    code: 'KG',
    dial_code: '+996',
    emoji: '🇰🇬',
    name: 'Kyrgyzstan',
    nameEmoji: '🇰🇬 Kyrgyzstan',
  },
  {
    code: 'LA',
    dial_code: '+856',
    emoji: '🇱🇦',
    name: 'Laos',
    nameEmoji: '🇱🇦 Laos',
  },
  {
    code: 'LV',
    dial_code: '+371',
    emoji: '🇱🇻',
    name: 'Latvia',
    nameEmoji: '🇱🇻 Latvia',
  },
  {
    code: 'LB',
    dial_code: '+961',
    emoji: '🇱🇧',
    name: 'Lebanon',
    nameEmoji: '🇱🇧 Lebanon',
  },
  {
    code: 'LS',
    dial_code: '+266',
    emoji: '🇱🇸',
    name: 'Lesotho',
    nameEmoji: '🇱🇸 Lesotho',
  },
  {
    code: 'LR',
    dial_code: '+231',
    emoji: '🇱🇷',
    name: 'Liberia',
    nameEmoji: '🇱🇷 Liberia',
  },
  {
    code: 'LY',
    dial_code: '+218',
    emoji: '🇱🇾',
    name: 'Libyan Arab Jamahiriya',
    nameEmoji: '🇱🇾 Libyan Arab Jamahiriya',
  },
  {
    code: 'LI',
    dial_code: '+423',
    emoji: '🇱🇮',
    name: 'Liechtenstein',
    nameEmoji: '🇱🇮 Liechtenstein',
  },
  {
    code: 'LT',
    dial_code: '+370',
    emoji: '🇱🇹',
    name: 'Lithuania',
    nameEmoji: '🇱🇹 Lithuania',
  },
  {
    code: 'LU',
    dial_code: '+352',
    emoji: '🇱🇺',
    name: 'Luxembourg',
    nameEmoji: '🇱🇺 Luxembourg',
  },
  {
    code: 'MO',
    dial_code: '+853',
    emoji: '🇲🇴',
    name: 'Macao',
    nameEmoji: '🇲🇴 Macao',
  },
  {
    code: 'MK',
    dial_code: '+389',
    emoji: '🇲🇰',
    name: 'Macedonia',
    nameEmoji: '🇲🇰 Macedonia',
  },
  {
    code: 'MG',
    dial_code: '+261',
    emoji: '🇲🇬',
    name: 'Madagascar',
    nameEmoji: '🇲🇬 Madagascar',
  },
  {
    code: 'MW',
    dial_code: '+265',
    emoji: '🇲🇼',
    name: 'Malawi',
    nameEmoji: '🇲🇼 Malawi',
  },
  {
    code: 'MY',
    dial_code: '+60',
    emoji: '🇲🇾',
    name: 'Malaysia',
    nameEmoji: '🇲🇾 Malaysia',
  },
  {
    code: 'MV',
    dial_code: '+960',
    emoji: '🇲🇻',
    name: 'Maldives',
    nameEmoji: '🇲🇻 Maldives',
  },
  {
    code: 'ML',
    dial_code: '+223',
    emoji: '🇲🇱',
    name: 'Mali',
    nameEmoji: '🇲🇱 Mali',
  },
  {
    code: 'MT',
    dial_code: '+356',
    emoji: '🇲🇹',
    name: 'Malta',
    nameEmoji: '🇲🇹 Malta',
  },
  {
    code: 'MH',
    dial_code: '+692',
    emoji: '🇲🇭',
    name: 'Marshall Islands',
    nameEmoji: '🇲🇭 Marshall Islands',
  },
  {
    code: 'MQ',
    dial_code: '+596',
    emoji: '🇲🇶',
    name: 'Martinique',
    nameEmoji: '🇲🇶 Martinique',
  },
  {
    code: 'MR',
    dial_code: '+222',
    emoji: '🇲🇷',
    name: 'Mauritania',
    nameEmoji: '🇲🇷 Mauritania',
  },
  {
    code: 'MU',
    dial_code: '+230',
    emoji: '🇲🇺',
    name: 'Mauritius',
    nameEmoji: '🇲🇺 Mauritius',
  },
  {
    code: 'YT',
    dial_code: '+262',
    emoji: '🇾🇹',
    name: 'Mayotte',
    nameEmoji: '🇾🇹 Mayotte',
  },
  {
    code: 'MX',
    dial_code: '+52',
    emoji: '🇲🇽',
    name: 'Mexico',
    nameEmoji: '🇲🇽 Mexico',
  },
  {
    code: 'FM',
    dial_code: '+691',
    emoji: '🇫🇲',
    name: 'Micronesia, Federated States of Micronesia',
    nameEmoji: '🇫🇲 Micronesia, Federated States of Micronesia',
  },
  {
    code: 'MD',
    dial_code: '+373',
    emoji: '🇲🇩',
    name: 'Moldova',
    nameEmoji: '🇲🇩 Moldova',
  },
  {
    code: 'MC',
    dial_code: '+377',
    emoji: '🇲🇨',
    name: 'Monaco',
    nameEmoji: '🇲🇨 Monaco',
  },
  {
    code: 'MN',
    dial_code: '+976',
    emoji: '🇲🇳',
    name: 'Mongolia',
    nameEmoji: '🇲🇳 Mongolia',
  },
  {
    code: 'ME',
    dial_code: '+382',
    emoji: '🇲🇪',
    name: 'Montenegro',
    nameEmoji: '🇲🇪 Montenegro',
  },
  {
    code: 'MS',
    dial_code: '+1664',
    emoji: '🇲🇸',
    name: 'Montserrat',
    nameEmoji: '🇲🇸 Montserrat',
  },
  {
    code: 'MA',
    dial_code: '+212',
    emoji: '🇲🇦',
    name: 'Morocco',
    nameEmoji: '🇲🇦 Morocco',
  },
  {
    code: 'MZ',
    dial_code: '+258',
    emoji: '🇲🇿',
    name: 'Mozambique',
    nameEmoji: '🇲🇿 Mozambique',
  },
  {
    code: 'MM',
    dial_code: '+95',
    emoji: '🇲🇲',
    name: 'Myanmar',
    nameEmoji: '🇲🇲 Myanmar',
  },
  {
    code: 'NA',
    dial_code: '+264',
    emoji: '🇳🇦',
    name: 'Namibia',
    nameEmoji: '🇳🇦 Namibia',
  },
  {
    code: 'NR',
    dial_code: '+674',
    emoji: '🇳🇷',
    name: 'Nauru',
    nameEmoji: '🇳🇷 Nauru',
  },
  {
    code: 'NP',
    dial_code: '+977',
    emoji: '🇳🇵',
    name: 'Nepal',
    nameEmoji: '🇳🇵 Nepal',
  },
  {
    code: 'NL',
    dial_code: '+31',
    emoji: '🇳🇱',
    name: 'Netherlands',
    nameEmoji: '🇳🇱 Netherlands',
  },
  {
    code: 'AN',
    dial_code: '+599',
    emoji: '🇧🇶',
    name: 'Netherlands Antilles',
    nameEmoji: '🇧🇶 Netherlands Antilles',
  },
  {
    code: 'NC',
    dial_code: '+687',
    emoji: '🇳🇨',
    name: 'New Caledonia',
    nameEmoji: '🇳🇨 New Caledonia',
  },
  {
    code: 'NZ',
    dial_code: '+64',
    emoji: '🇳🇿',
    name: 'New Zealand',
    nameEmoji: '🇳🇿 New Zealand',
  },
  {
    code: 'NI',
    dial_code: '+505',
    emoji: '🇳🇮',
    name: 'Nicaragua',
    nameEmoji: '🇳🇮 Nicaragua',
  },
  {
    code: 'NE',
    dial_code: '+227',
    emoji: '🇳🇪',
    name: 'Niger',
    nameEmoji: '🇳🇪 Niger',
  },
  {
    code: 'NG',
    dial_code: '+234',
    emoji: '🇳🇬',
    name: 'Nigeria',
    nameEmoji: '🇳🇬 Nigeria',
  },
  {
    code: 'NU',
    dial_code: '+683',
    emoji: '🇳🇺',
    name: 'Niue',
    nameEmoji: '🇳🇺 Niue',
  },
  {
    code: 'NF',
    dial_code: '+672',
    emoji: '🇳🇫',
    name: 'Norfolk Island',
    nameEmoji: '🇳🇫 Norfolk Island',
  },
  {
    code: 'MP',
    dial_code: '+1670',
    emoji: '🇲🇵',
    name: 'Northern Mariana Islands',
    nameEmoji: '🇲🇵 Northern Mariana Islands',
  },
  {
    code: 'NO',
    dial_code: '+47',
    emoji: '🇳🇴',
    name: 'Norway',
    nameEmoji: '🇳🇴 Norway',
  },
  {
    code: 'OM',
    dial_code: '+968',
    emoji: '🇴🇲',
    name: 'Oman',
    nameEmoji: '🇴🇲 Oman',
  },
  {
    code: 'PK',
    dial_code: '+92',
    emoji: '🇵🇰',
    name: 'Pakistan',
    nameEmoji: '🇵🇰 Pakistan',
  },
  {
    code: 'PW',
    dial_code: '+680',
    emoji: '🇵🇼',
    name: 'Palau',
    nameEmoji: '🇵🇼 Palau',
  },
  {
    code: 'PS',
    dial_code: '+970',
    emoji: '🇵🇸',
    name: 'Palestinian Territory, Occupied',
    nameEmoji: '🇵🇸 Palestinian Territory, Occupied',
  },
  {
    code: 'PA',
    dial_code: '+507',
    emoji: '🇵🇦',
    name: 'Panama',
    nameEmoji: '🇵🇦 Panama',
  },
  {
    code: 'PG',
    dial_code: '+675',
    emoji: '🇵🇬',
    name: 'Papua New Guinea',
    nameEmoji: '🇵🇬 Papua New Guinea',
  },
  {
    code: 'PY',
    dial_code: '+595',
    emoji: '🇵🇾',
    name: 'Paraguay',
    nameEmoji: '🇵🇾 Paraguay',
  },
  {
    code: 'PE',
    dial_code: '+51',
    emoji: '🇵🇪',
    name: 'Peru',
    nameEmoji: '🇵🇪 Peru',
  },
  {
    code: 'PH',
    dial_code: '+63',
    emoji: '🇵🇭',
    name: 'Philippines',
    nameEmoji: '🇵🇭 Philippines',
  },
  {
    code: 'PN',
    dial_code: '+872',
    emoji: '🇵🇳',
    name: 'Pitcairn',
    nameEmoji: '🇵🇳 Pitcairn',
  },
  {
    code: 'PL',
    dial_code: '+48',
    emoji: '🇵🇱',
    name: 'Poland',
    nameEmoji: '🇵🇱 Poland',
  },
  {
    code: 'PT',
    dial_code: '+351',
    emoji: '🇵🇹',
    name: 'Portugal',
    nameEmoji: '🇵🇹 Portugal',
  },
  {
    code: 'PR',
    dial_code: '+1939',
    emoji: '🇵🇷',
    name: 'Puerto Rico',
    nameEmoji: '🇵🇷 Puerto Rico',
  },
  {
    code: 'QA',
    dial_code: '+974',
    emoji: '🇶🇦',
    name: 'Qatar',
    nameEmoji: '🇶🇦 Qatar',
  },
  {
    code: 'RO',
    dial_code: '+40',
    emoji: '🇷🇴',
    name: 'Romania',
    nameEmoji: '🇷🇴 Romania',
  },
  {
    code: 'RU',
    dial_code: '+7',
    emoji: '🇷🇺',
    name: 'Russia',
    nameEmoji: '🇷🇺 Russia',
  },
  {
    code: 'RW',
    dial_code: '+250',
    emoji: '🇷🇼',
    name: 'Rwanda',
    nameEmoji: '🇷🇼 Rwanda',
  },
  {
    code: 'RE',
    dial_code: '+262',
    emoji: '🇷🇪',
    name: 'Reunion',
    nameEmoji: '🇷🇪 Reunion',
  },
  {
    code: 'BL',
    dial_code: '+590',
    emoji: '🇧🇱',
    name: 'Saint Barthelemy',
    nameEmoji: '🇧🇱 Saint Barthelemy',
  },
  {
    code: 'SH',
    dial_code: '+290',
    emoji: '🇸🇭',
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    nameEmoji: '🇸🇭 Saint Helena, Ascension and Tristan Da Cunha',
  },
  {
    code: 'KN',
    dial_code: '+1869',
    emoji: '🇰🇳',
    name: 'Saint Kitts and Nevis',
    nameEmoji: '🇰🇳 Saint Kitts and Nevis',
  },
  {
    code: 'LC',
    dial_code: '+1758',
    emoji: '🇱🇨',
    name: 'Saint Lucia',
    nameEmoji: '🇱🇨 Saint Lucia',
  },
  {
    code: 'MF',
    dial_code: '+590',
    emoji: '🇲🇫',
    name: 'Saint Martin',
    nameEmoji: '🇲🇫 Saint Martin',
  },
  {
    code: 'PM',
    dial_code: '+508',
    emoji: '🇵🇲',
    name: 'Saint Pierre and Miquelon',
    nameEmoji: '🇵🇲 Saint Pierre and Miquelon',
  },
  {
    code: 'VC',
    dial_code: '+1784',
    emoji: '🇻🇨',
    name: 'Saint Vincent and the Grenadines',
    nameEmoji: '🇻🇨 Saint Vincent and the Grenadines',
  },
  {
    code: 'WS',
    dial_code: '+685',
    emoji: '🇼🇸',
    name: 'Samoa',
    nameEmoji: '🇼🇸 Samoa',
  },
  {
    code: 'SM',
    dial_code: '+378',
    emoji: '🇸🇲',
    name: 'San Marino',
    nameEmoji: '🇸🇲 San Marino',
  },
  {
    code: 'ST',
    dial_code: '+239',
    emoji: '🇸🇹',
    name: 'Sao Tome and Principe',
    nameEmoji: '🇸🇹 Sao Tome and Principe',
  },
  {
    code: 'SA',
    dial_code: '+966',
    emoji: '🇸🇦',
    name: 'Saudi Arabia',
    nameEmoji: '🇸🇦 Saudi Arabia',
  },
  {
    code: 'SN',
    dial_code: '+221',
    emoji: '🇸🇳',
    name: 'Senegal',
    nameEmoji: '🇸🇳 Senegal',
  },
  {
    code: 'RS',
    dial_code: '+381',
    emoji: '🇷🇸',
    name: 'Serbia',
    nameEmoji: '🇷🇸 Serbia',
  },
  {
    code: 'SC',
    dial_code: '+248',
    emoji: '🇸🇨',
    name: 'Seychelles',
    nameEmoji: '🇸🇨 Seychelles',
  },
  {
    code: 'SL',
    dial_code: '+232',
    emoji: '🇸🇱',
    name: 'Sierra Leone',
    nameEmoji: '🇸🇱 Sierra Leone',
  },
  {
    code: 'SG',
    dial_code: '+65',
    emoji: '🇸🇬',
    name: 'Singapore',
    nameEmoji: '🇸🇬 Singapore',
  },
  {
    code: 'SK',
    dial_code: '+421',
    emoji: '🇸🇰',
    name: 'Slovakia',
    nameEmoji: '🇸🇰 Slovakia',
  },
  {
    code: 'SI',
    dial_code: '+386',
    emoji: '🇸🇮',
    name: 'Slovenia',
    nameEmoji: '🇸🇮 Slovenia',
  },
  {
    code: 'SB',
    dial_code: '+677',
    emoji: '🇸🇧',
    name: 'Solomon Islands',
    nameEmoji: '🇸🇧 Solomon Islands',
  },
  {
    code: 'SO',
    dial_code: '+252',
    emoji: '🇸🇴',
    name: 'Somalia',
    nameEmoji: '🇸🇴 Somalia',
  },
  {
    code: 'ZA',
    dial_code: '+27',
    emoji: '🇿🇦',
    name: 'South Africa',
    nameEmoji: '🇿🇦 South Africa',
  },
  {
    code: 'SS',
    dial_code: '+211',
    emoji: '🇸🇸',
    name: 'South Sudan',
    nameEmoji: '🇸🇸 South Sudan',
  },
  {
    code: 'GS',
    dial_code: '+500',
    emoji: '🇬🇸',
    name: 'South Georgia and the South Sandwich Islands',
    nameEmoji: '🇬🇸 South Georgia and the South Sandwich Islands',
  },
  {
    code: 'ES',
    dial_code: '+34',
    emoji: '🇪🇸',
    name: 'Spain',
    nameEmoji: '🇪🇸 Spain',
  },
  {
    code: 'LK',
    dial_code: '+94',
    emoji: '🇱🇰',
    name: 'Sri Lanka',
    nameEmoji: '🇱🇰 Sri Lanka',
  },
  {
    code: 'SD',
    dial_code: '+249',
    emoji: '🇸🇩',
    name: 'Sudan',
    nameEmoji: '🇸🇩 Sudan',
  },
  {
    code: 'SR',
    dial_code: '+597',
    emoji: '🇸🇷',
    name: 'Suriname',
    nameEmoji: '🇸🇷 Suriname',
  },
  {
    code: 'SJ',
    dial_code: '+47',
    emoji: '🇸🇯',
    name: 'Svalbard and Jan Mayen',
    nameEmoji: '🇸🇯 Svalbard and Jan Mayen',
  },
  {
    code: 'SZ',
    dial_code: '+268',
    emoji: '🇸🇿',
    name: 'Swaziland',
    nameEmoji: '🇸🇿 Swaziland',
  },
  {
    code: 'SE',
    dial_code: '+46',
    emoji: '🇸🇪',
    name: 'Sweden',
    nameEmoji: '🇸🇪 Sweden',
  },
  {
    code: 'CH',
    dial_code: '+41',
    emoji: '🇨🇭',
    name: 'Switzerland',
    nameEmoji: '🇨🇭 Switzerland',
  },
  {
    code: 'SY',
    dial_code: '+963',
    emoji: '🇸🇾',
    name: 'Syrian Arab Republic',
    nameEmoji: '🇸🇾 Syrian Arab Republic',
  },
  {
    code: 'TW',
    dial_code: '+886',
    emoji: '🇹🇼',
    name: 'Taiwan',
    nameEmoji: '🇹🇼 Taiwan',
  },
  {
    code: 'TJ',
    dial_code: '+992',
    emoji: '🇹🇯',
    name: 'Tajikistan',
    nameEmoji: '🇹🇯 Tajikistan',
  },
  {
    code: 'TZ',
    dial_code: '+255',
    emoji: '🇹🇿',
    name: 'Tanzania, United Republic of Tanzania',
    nameEmoji: '🇹🇿 Tanzania, United Republic of Tanzania',
  },
  {
    code: 'TH',
    dial_code: '+66',
    emoji: '🇹🇭',
    name: 'Thailand',
    nameEmoji: '🇹🇭 Thailand',
  },
  {
    code: 'TL',
    dial_code: '+670',
    emoji: '🇹🇱',
    name: 'Timor-Leste',
    nameEmoji: '🇹🇱 Timor-Leste',
  },
  {
    code: 'TG',
    dial_code: '+228',
    emoji: '🇹🇬',
    name: 'Togo',
    nameEmoji: '🇹🇬 Togo',
  },
  {
    code: 'TK',
    dial_code: '+690',
    emoji: '🇹🇰',
    name: 'Tokelau',
    nameEmoji: '🇹🇰 Tokelau',
  },
  {
    code: 'TO',
    dial_code: '+676',
    emoji: '🇹🇴',
    name: 'Tonga',
    nameEmoji: '🇹🇴 Tonga',
  },
  {
    code: 'TT',
    dial_code: '+1868',
    emoji: '🇹🇹',
    name: 'Trinidad and Tobago',
    nameEmoji: '🇹🇹 Trinidad and Tobago',
  },
  {
    code: 'TN',
    dial_code: '+216',
    emoji: '🇹🇳',
    name: 'Tunisia',
    nameEmoji: '🇹🇳 Tunisia',
  },
  {
    code: 'TR',
    dial_code: '+90',
    emoji: '🇹🇷',
    name: 'Turkey',
    nameEmoji: '🇹🇷 Turkey',
  },
  {
    code: 'TM',
    dial_code: '+993',
    emoji: '🇹🇲',
    name: 'Turkmenistan',
    nameEmoji: '🇹🇲 Turkmenistan',
  },
  {
    code: 'TC',
    dial_code: '+1649',
    emoji: '🇹🇨',
    name: 'Turks and Caicos Islands',
    nameEmoji: '🇹🇨 Turks and Caicos Islands',
  },
  {
    code: 'TV',
    dial_code: '+688',
    emoji: '🇹🇻',
    name: 'Tuvalu',
    nameEmoji: '🇹🇻 Tuvalu',
  },
  {
    code: 'UG',
    dial_code: '+256',
    emoji: '🇺🇬',
    name: 'Uganda',
    nameEmoji: '🇺🇬 Uganda',
  },
  {
    code: 'UA',
    dial_code: '+380',
    emoji: '🇺🇦',
    name: 'Ukraine',
    nameEmoji: '🇺🇦 Ukraine',
  },
  {
    code: 'AE',
    dial_code: '+971',
    emoji: '🇦🇪',
    name: 'United Arab Emirates',
    nameEmoji: '🇦🇪 United Arab Emirates',
  },
  {
    code: 'GB',
    dial_code: '+44',
    emoji: '🇬🇧',
    name: 'United Kingdom',
    nameEmoji: '🇬🇧 United Kingdom',
  },
  {
    code: 'US',
    dial_code: '+1',
    emoji: '🇺🇸',
    name: 'United States',
    nameEmoji: '🇺🇸 United States',
  },
  {
    code: 'UY',
    dial_code: '+598',
    emoji: '🇺🇾',
    name: 'Uruguay',
    nameEmoji: '🇺🇾 Uruguay',
  },
  {
    code: 'UZ',
    dial_code: '+998',
    emoji: '🇺🇿',
    name: 'Uzbekistan',
    nameEmoji: '🇺🇿 Uzbekistan',
  },
  {
    code: 'VU',
    dial_code: '+678',
    emoji: '🇻🇺',
    name: 'Vanuatu',
    nameEmoji: '🇻🇺 Vanuatu',
  },
  {
    code: 'VE',
    dial_code: '+58',
    emoji: '🇻🇪',
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    nameEmoji: '🇻🇪 Venezuela, Bolivarian Republic of Venezuela',
  },
  {
    code: 'VN',
    dial_code: '+84',
    emoji: '🇻🇳',
    name: 'Vietnam',
    nameEmoji: '🇻🇳 Vietnam',
  },
  {
    code: 'VG',
    dial_code: '+1284',
    emoji: '🇻🇬',
    name: 'Virgin Islands, British',
    nameEmoji: '🇻🇬 Virgin Islands, British',
  },
  {
    code: 'VI',
    dial_code: '+1340',
    emoji: '🇻🇮',
    name: 'Virgin Islands, U.S.',
    nameEmoji: '🇻🇮 Virgin Islands, U.S.',
  },
  {
    code: 'WF',
    dial_code: '+681',
    emoji: '🇼🇫',
    name: 'Wallis and Futuna',
    nameEmoji: '🇼🇫 Wallis and Futuna',
  },
  {
    code: 'YE',
    dial_code: '+967',
    emoji: '🇾🇪',
    name: 'Yemen',
    nameEmoji: '🇾🇪 Yemen',
  },
  {
    code: 'ZM',
    dial_code: '+260',
    emoji: '🇿🇲',
    name: 'Zambia',
    nameEmoji: '🇿🇲 Zambia',
  },
  {
    code: 'ZW',
    dial_code: '+263',
    emoji: '🇿🇼',
    name: 'Zimbabwe',
    nameEmoji: '🇿🇼 Zimbabwe',
  },
];
const NEW_SEC_CURRENCIES = [
  {
    currency: 'America (United States) Dollars - USD',
    code: 'USD',
    symbol: '$',
    countryCode: 'US',
  },
  {
    currency: 'Afghanistan Afghanis - AFN',
    code: 'AFN',
    symbol: '؋',
    countryCode: 'AF',
  },
  {
    currency: 'Albania Leke - ALL',
    code: 'ALL',
    symbol: 'Lek',
    countryCode: 'AL',
  },
  {
    currency: 'Algeria Dinars - DZD',
    code: 'DZD',
    symbol: 'د.ج',
    countryCode: 'DZ',
  },
  {
    currency: 'Argentina Pesos - ARS',
    code: 'ARS',
    symbol: '$',
    countryCode: 'AR',
  },
  {
    currency: 'Australia Dollars - AUD',
    code: 'AUD',
    symbol: '$',
    countryCode: 'AU',
  },
  {
    currency: 'Austria Schillings - ATS',
    code: 'ATS',
    symbol: 'S',
    countryCode: 'AT',
  },
  {
    currency: 'Bahamas Dollars - BSD',
    code: 'BSD',
    symbol: '$',
    countryCode: 'BS',
  },
  {
    currency: 'Bahrain Dinars - BHD',
    code: 'BHD',
    symbol: '.د.ب',
    countryCode: 'BH',
  },
  {
    currency: 'Bangladesh Taka - BDT',
    code: 'BDT',
    symbol: '৳',
    countryCode: 'BD',
  },
  {
    currency: 'Barbados Dollars - BBD',
    code: 'BBD',
    symbol: '$',
    countryCode: 'BB',
  },
  {
    currency: 'Belgium Francs - BEF',
    code: 'BEF',
    symbol: 'fr.',
    countryCode: 'BE',
  },
  {
    currency: 'Bermuda Dollars - BMD',
    code: 'BMD',
    symbol: '$',
    countryCode: 'BM',
  },
  {
    currency: 'Brazil Reais - BRL',
    code: 'BRL',
    symbol: 'R$',
    countryCode: 'BR',
  },
  {
    currency: 'Bulgaria Leva - BGN',
    code: 'BGN',
    symbol: 'лв',
    countryCode: 'BG',
  },
  {
    currency: 'Canada Dollars - CAD',
    code: 'CAD',
    symbol: '$',
    countryCode: 'CA',
  },
  {
    currency: 'CFA BCEAO Francs - XOF',
    code: 'XOF',
    symbol: 'Fr',
    countryCode: 'CI',
  },
  {
    currency: 'CFA BEAC Francs - XAF',
    code: 'XAF',
    symbol: 'Fr',
    countryCode: 'CM',
  },
  {
    currency: 'Chile Pesos - CLP',
    code: 'CLP',
    symbol: '$',
    countryCode: 'CL',
  },
  {
    currency: 'China Yuan Renminbi - CNY',
    code: 'CNY',
    symbol: '¥',
    countryCode: 'CN',
  },
  {
    currency: 'RMB (China Yuan Renminbi) - CNY',
    code: 'CNY',
    symbol: '¥',
    countryCode: 'CN',
  },
  {
    currency: 'Colombia Pesos - COP',
    code: 'COP',
    symbol: '$',
    countryCode: 'CO',
  },
  {
    currency: 'CFP Francs - XPF',
    code: 'XPF',
    symbol: 'Fr',
    countryCode: 'PF',
  },
  {
    currency: 'Costa Rica Colones - CRC',
    code: 'CRC',
    symbol: '₡',
    countryCode: 'CR',
  },
  {
    currency: 'Croatia Kuna - HRK',
    code: 'HRK',
    symbol: 'kn',
    countryCode: 'HR',
  },
  {
    currency: 'Cyprus Pounds - CYP',
    code: 'CYP',
    symbol: '£',
    countryCode: 'CY',
  },
  {
    currency: 'Czech Republic Koruny - CZK',
    code: 'CZK',
    symbol: 'Kč',
    countryCode: 'CZ',
  },
  {
    currency: 'Denmark Kroner - DKK',
    code: 'DKK',
    symbol: 'kr',
    countryCode: 'DK',
  },
  {
    currency: 'Deutsche (Germany) Marks - DEM',
    code: 'DEM',
    symbol: 'DM',
    countryCode: 'DE',
  },
  {
    currency: 'Dominican Republic Pesos - DOP',
    code: 'DOP',
    symbol: 'RD$',
    countryCode: 'DO',
  },
  {
    currency: 'Dutch (Netherlands) Guilders - NLG',
    code: 'NLG',
    symbol: 'ƒ',
    countryCode: 'NL',
  },
  {
    currency: 'Eastern Caribbean Dollars - XCD',
    code: 'XCD',
    symbol: '$',
    countryCode: 'VC',
  },
  {
    currency: 'Egypt Pounds - EGP',
    code: 'EGP',
    symbol: 'ج.م',
    countryCode: 'EG',
  },
  {
    currency: 'Estonia Krooni - EEK',
    code: 'EEK',
    symbol: 'kr',
    countryCode: 'EE',
  },
  { currency: 'Euro - EUR', code: 'EUR', symbol: '€', countryCode: 'EU' },
  {
    currency: 'Fiji Dollars - FJD',
    code: 'FJD',
    symbol: '$',
    countryCode: 'FJ',
  },
  {
    currency: 'Finland Markkaa - FIM',
    code: 'FIM',
    symbol: 'mk',
    countryCode: 'FI',
  },
  {
    currency: 'France Francs - FRF*',
    code: 'FRF*',
    symbol: 'Fr',
    countryCode: 'FR',
  },
  {
    currency: 'Germany Deutsche Marks - DEM',
    code: 'DEM',
    symbol: 'DM',
    countryCode: 'DE',
  },
  { currency: 'Gold Ounces - XAU', code: 'XAU', symbol: '', countryCode: '' },
  {
    currency: 'Greece Drachmae - GRD',
    code: 'GRD',
    symbol: 'Δρ',
    countryCode: 'GR',
  },
  {
    currency: 'Guatemalan Quetzal - GTQ',
    code: 'GTQ',
    symbol: 'Q',
    countryCode: 'GT',
  },
  {
    currency: 'Holland (Netherlands) Guilders - NLG',
    code: 'NLG',
    symbol: 'ƒ',
    countryCode: 'NL',
  },
  {
    currency: 'Hong Kong Dollars - HKD',
    code: 'HKD',
    symbol: 'HK$',
    countryCode: 'HK',
  },
  {
    currency: 'Hungary Forint - HUF',
    code: 'HUF',
    symbol: 'Ft',
    countryCode: 'HU',
  },
  {
    currency: 'Iceland Kronur - ISK',
    code: 'ISK',
    symbol: 'kr',
    countryCode: 'IS',
  },
  {
    currency: 'IMF Special Drawing Right - XDR',
    code: 'XDR',
    symbol: '',
    countryCode: 'XM',
  },
  {
    currency: 'India Rupees - INR',
    code: 'INR',
    symbol: '₹',
    countryCode: 'IN',
  },
  {
    currency: 'Indonesia Rupiahs - IDR',
    code: 'IDR',
    symbol: 'Rp',
    countryCode: 'ID',
  },
  {
    currency: 'Iran Rials - IRR',
    code: 'IRR',
    symbol: 'ریال',
    countryCode: 'IR',
  },
  {
    currency: 'Iraq Dinars - IQD',
    code: 'IQD',
    symbol: 'د.ع',
    countryCode: 'IQ',
  },
  {
    currency: 'Ireland Pounds - IEP*',
    code: 'IEP*',
    symbol: '£',
    countryCode: 'IE',
  },
  {
    currency: 'Israel New Shekels - ILS',
    code: 'ILS',
    symbol: '₪',
    countryCode: 'IL',
  },
  {
    currency: 'Italy Lire - ITL*',
    code: 'ITL*',
    symbol: '₤',
    countryCode: 'IT',
  },
  {
    currency: 'Jamaica Dollars - JMD',
    code: 'JMD',
    symbol: 'J$',
    countryCode: 'JM',
  },
  { currency: 'Japan Yen - JPY', code: 'JPY', symbol: '¥', countryCode: 'JP' },
  {
    currency: 'Jordan Dinars - JOD',
    code: 'JOD',
    symbol: 'د.أ',
    countryCode: 'JO',
  },
  {
    currency: 'Kenya Shillings - KES',
    code: 'KES',
    symbol: 'KSh',
    countryCode: 'KE',
  },
  {
    currency: 'Korea (South) Won - KRW',
    code: 'KRW',
    symbol: '₩',
    countryCode: 'KR',
  },
  {
    currency: 'Kuwait Dinars - KWD',
    code: 'KWD',
    symbol: 'د.ك',
    countryCode: 'KW',
  },
  {
    currency: 'Lebanon Pounds - LBP',
    code: 'LBP',
    symbol: 'ل.ل',
    countryCode: 'LB',
  },
  {
    currency: 'Luxembourg Francs - LUF',
    code: 'LUF',
    symbol: 'Fr',
    countryCode: 'LU',
  },
  {
    currency: 'Malaysia Ringgits - MYR',
    code: 'MYR',
    symbol: 'RM',
    countryCode: 'MY',
  },
  {
    currency: 'Malta Liri - MTL',
    code: 'MTL',
    symbol: 'Lm',
    countryCode: 'MT',
  },
  {
    currency: 'Mauritius Rupees - MUR',
    code: 'MUR',
    symbol: '₨',
    countryCode: 'MU',
  },
  {
    currency: 'Mexico Pesos - MXN',
    code: 'MXN',
    symbol: '$',
    countryCode: 'MX',
  },
  {
    currency: 'Morocco Dirhams - MAD',
    code: 'MAD',
    symbol: 'د.م.',
    countryCode: 'MA',
  },
  {
    currency: 'Netherlands Guilders - NLG',
    code: 'NLG',
    symbol: 'ƒ',
    countryCode: 'NL',
  },
  {
    currency: 'New Zealand Dollars - NZD',
    code: 'NZD',
    symbol: '$',
    countryCode: 'NZ',
  },
  {
    currency: 'Norway Kroner - NOK',
    code: 'NOK',
    symbol: 'kr',
    countryCode: 'NO',
  },
  {
    currency: 'Oman Rials - OMR',
    code: 'OMR',
    symbol: 'ر.ع.',
    countryCode: 'OM',
  },
  {
    currency: 'Pakistan Rupees - PKR',
    code: 'PKR',
    symbol: '₨',
    countryCode: 'PK',
  },
  {
    currency: 'Palladium Ounces - XPD',
    code: 'XPD',
    symbol: '',
    countryCode: '',
  },
  {
    currency: 'Peru Nuevos Soles - PEN',
    code: 'PEN',
    symbol: 'S/',
    countryCode: 'PE',
  },
  {
    currency: 'Philippines Pesos - PHP',
    code: 'PHP',
    symbol: '₱',
    countryCode: 'PH',
  },
  {
    currency: 'Platinum Ounces - XPT',
    code: 'XPT',
    symbol: '',
    countryCode: '',
  },
  {
    currency: 'Poland Zlotych - PLN',
    code: 'PLN',
    symbol: 'zł',
    countryCode: 'PL',
  },
  {
    currency: 'Portugal Escudos - PTE',
    code: 'PTE',
    symbol: '₡',
    countryCode: 'PT',
  },
  {
    currency: 'Qatar Riyals - QAR',
    code: 'QAR',
    symbol: 'ر.ق',
    countryCode: 'QA',
  },
  {
    currency: 'Romania New Lei - RON',
    code: 'RON',
    symbol: 'lei',
    countryCode: 'RO',
  },
  {
    currency: 'Romania Lei - ROL',
    code: 'ROL',
    symbol: 'lei',
    countryCode: 'RO',
  },
  {
    currency: 'Russia Rubles - RUB',
    code: 'RUB',
    symbol: '₽',
    countryCode: 'RU',
  },
  {
    currency: 'Saudi Arabia Riyals - SAR',
    code: 'SAR',
    symbol: 'ر.س',
    countryCode: 'SA',
  },
  { currency: 'Silver Ounces - XAG', code: 'XAG', symbol: '', countryCode: '' },
  {
    currency: 'Singapore Dollars - SGD',
    code: 'SGD',
    symbol: 'S$',
    countryCode: 'SG',
  },
  {
    currency: 'Slovakia Koruny - SKK',
    code: 'SKK',
    symbol: 'Sk',
    countryCode: 'SK',
  },
  {
    currency: 'Slovenia Tolars - SIT',
    code: 'SIT',
    symbol: 'SIT',
    countryCode: 'SI',
  },
  {
    currency: 'South Africa Rand - ZAR',
    code: 'ZAR',
    symbol: 'R',
    countryCode: 'ZA',
  },
  {
    currency: 'South Korea Won - KRW',
    code: 'KRW',
    symbol: '₩',
    countryCode: 'KR',
  },
  {
    currency: 'Spain Pesetas - ESP',
    code: 'ESP',
    symbol: '₧',
    countryCode: 'ES',
  },
  {
    currency: 'Special Drawing Rights (IMF) - XDR',
    code: 'XDR',
    symbol: '',
    countryCode: 'XM',
  },
  {
    currency: 'Sri Lanka Rupees - LKR',
    code: 'LKR',
    symbol: '₨',
    countryCode: 'LK',
  },
  {
    currency: 'Sudan Dinars - SDD',
    code: 'SDD',
    symbol: 'د.س',
    countryCode: 'SD',
  },
  {
    currency: 'Sweden Kronor - SEK',
    code: 'SEK',
    symbol: 'kr',
    countryCode: 'SE',
  },
  {
    currency: 'Switzerland Francs - CHF',
    code: 'CHF',
    symbol: 'Fr',
    countryCode: 'CH',
  },
  {
    currency: 'Taiwan New Dollars - TWD',
    code: 'TWD',
    symbol: 'NT$',
    countryCode: 'TW',
  },
  {
    currency: 'Thailand Baht - THB',
    code: 'THB',
    symbol: '฿',
    countryCode: 'TH',
  },
  {
    currency: 'Trinidad and Tobago Dollars - TTD',
    code: 'TTD',
    symbol: 'TT$',
    countryCode: 'TT',
  },
  {
    currency: 'Tunisia Dinars - TND',
    code: 'TND',
    symbol: 'د.ت',
    countryCode: 'TN',
  },
  {
    currency: 'Turkey New Lira - TRY',
    code: 'TRY',
    symbol: '₺',
    countryCode: 'TR',
  },
  {
    currency: 'United Arab Emirates Dirhams - AED',
    code: 'AED',
    symbol: 'د.إ',
    countryCode: 'AE',
  },
  {
    currency: 'United Kingdom Pounds - GBP',
    code: 'GBP',
    symbol: '£',
    countryCode: 'GB',
  },
  {
    currency: 'United States Dollars - USD',
    code: 'USD',
    symbol: '$',
    countryCode: 'US',
  },
  {
    currency: 'Venezuela Bolivares - VEB',
    code: 'VEB',
    symbol: 'Bs',
    countryCode: 'VE',
  },
  {
    currency: 'Vietnam Dong - VND',
    code: 'VND',
    symbol: '₫',
    countryCode: 'VN',
  },
  {
    currency: 'Zambia Kwacha - ZMK',
    code: 'ZMK',
    symbol: 'ZK',
    countryCode: 'ZM',
  },
];
const APP_NAME_CODESS = {
  HYBRID_RESEARCH_CENTER: 'hrc',
  EMIRATES_RESEARCH_CENTER: 'erc',
  DIGITAL_SKY_SERVICES: 'dss',
  PRO_WRITING_FIRM:'prf'
};


export {
    CATEGORY_LEVELS,
    COUNTRY_DETAILS,
    APP_NAME_CODESS,
    NEW_SEC_CURRENCIES
  };